### ISSUE TITLE
Various reg UI improvements

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax-ui#41]
This is a consolidation of the medium priority items. The high priority items are separate individual issues.

The links in this list are to the original individual issues that you can look at for details.

- [x] [back button after external link does not come back to correct page](https://github.com/open-horizon/anax/issues/79) (#66)
- [ ] [improvements requested by egan](https://github.com/open-horizon/anax-ui/issues/12):
    - [x] change default pw warning to be less fear-inducing if the device is behind a firewall (#64)
    - [ ] provide a button in the UI to change the device pw (was also in [issue 20] (#63)
 (https://github.com/open-horizon/anax-ui/issues/20) )
    - [ ] add embedded map or link to the bluehorizon.network/map to show the location of this device (was also in [issue 14](https://github.com/open-horizon/anax-ui/issues/14) ) (#65)
- [x] [add expand/collapse carrot on the terminated agreements to show all terminated agreements and their reasons](https://github.com/open-horizon/anax/issues/71) (#61)
- [x] [add option to show all the agreement attributes and all the status details](https://github.com/open-horizon/anax/issues/70) (#62)
- [x] [visibility toggle for password inputs](https://github.com/open-horizon/anax-ui/issues/19) - in snap 85 (armhf) and 86 (x86). version 2.0.3 (#60)

**Comment by linggao** [comment]
PR: https://github.com/open-horizon/bluehorizon-snap/pull/40

**Comment by linggao** [comment]
Visibility toggle for password inputs is built in snap 85 (armhf) and 86 (x86). version 2.0.3

**Comment by linggao** [comment]
"visibility toggle for password inputs" in snap 85 works when the registration page was first brought up. However, the toggle button went away from the password field when the "I have an account with Horizon" check box is checked.

**Comment by varatep** [comment]
@bmpotter I'm not sure if this should be labeled as an epic. @linggao and I agreed that this issue should be broken into multiple for easier tracking of individual items. Let me know your thoughts on this.

**Comment by bmpotter** [comment]
I originally consolidated them into this issue because you weren't able to work on them due to other priorities and they were just clouding the zenhub board. If you are going to work on them soon, i don't mind you breaking them out into individual issues, i agree they are easier to track that way. Looks like you have done that, but most are in the Icebox column. Why? I use the Icebox column for issues that we don't want to pay any attention to, at least for now, due to changing priorities.

**Comment by bmpotter** [comment]
The remaining bullets have separate issues open for them
